name: "HAVNC"
description: "VNC straight to your dashboard"
version: "0.0.5"
slug: "havnc"
init: false
full_access: true
#ingress: falase
#ingress_port: 8080
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  8080/tcp: 8080
  #  5900/tcp: 5900
